apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-agent-config
  namespace: wazuh
data:
  ossec.conf: |
    <ossec_config>
      <client>
        <server>
          <address>wazuh-manager-service</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>
      </client>
      <syscheck>
        <directories>/host/etc</directories>
        <directories>/host/var/log</directories>
      </syscheck>
      <!-- meer config hier -->
    </ossec_config>
