# PersistentVolume voor de eerste PVC voor de wazuh-indexer.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-indexer-pv  # Naam van dit PV, specifiek voor de indexer.
spec:
  capacity:
    storage: 5Gi # Grootte van deze volume, moet >= PVC request zijn even kijken of 5g genoeg is.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: wazuh-storage  # Verwijs naar dezelfde StorageClass
  hostPath:
    path: "/etc/kubernetes-volumes/wazuh/wazuh-indexer"   # Unieke directory voor de indexer data.
    type: DirectoryOrCreate       # Maakt directory aan indien niet aanwezig.
  nodeAffinity: # Node affinity zorgt ervoor dat deze PV alleen aan een pod op een specifieke node gebonden kan worden.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/storage
          operator: In
          values:
          - "true"
---
# PersistentVolume voor de tweede PVC voor de wazuh-manager-master.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-master-pv  # Naam van dit PV voor de manager-master.
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: wazuh-storage
  hostPath:
    path: "/etc/kubernetes-volumes/wazuh/wazuh-manager-master"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/storage
          operator: In
          values:
          - "true"
---
# PersistentVolume voor de derde PVC, bijvoorbeeld voor de wazuh-manager-worker.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-worker-pv  # Naam van dit PV voor de manager-worker.
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: wazuh-storage
  hostPath:
    path: "/etc/kubernetes-volumes/wazuh/wazuh-manager-worker"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/storage
          operator: In
          values:
          - "true"
