# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization # Hiermee wordt aangegeven dat dit een Kustomization resource betreft
resources: 
- ../../wazuh # Dit geeft aan dat de resources in de map ../../wazuh bevinden onderdeel zijn van deze kustomization. Kustomize zal daarmee het Kustomization yaml bestand in wazuh_CTFchallenge/wazuh inladen
patches: # Een lijst van patch-bestanden die toegepast worden deze patches bevinden zich in de map wazuh_CTFchallenge/envs/local-env
- path: indexer-resources.yaml
- path: wazuh-resources.yaml
